definitions:
  handler.BaseResponse:
    properties:
      code:
        example: 1
        type: integer
      data:
        $ref: '#/definitions/handler.Data'
        type: object
      message:
        example: ok
        type: string
    type: object
  handler.Data:
    properties:
      token:
        example: abcd.abcd.abcd
        type: string
    type: object
  handler.GetResponse:
    properties:
      code:
        example: 1
        type: integer
      data:
        $ref: '#/definitions/handler.UserInfoResponse'
        type: object
      message:
        example: ok
        type: string
    type: object
  handler.UserChangePwdRequest:
    properties:
      account:
        type: string
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  handler.UserInfoResponse:
    properties:
      birthday:
        type: string
      gender:
        type: integer
      name:
        type: string
    type: object
  handler.UserLoginRequest:
    properties:
      account:
        type: string
      password:
        type: string
    type: object
  handler.UserRegisterRequest:
    properties:
      account:
        type: string
      birthday:
        type: string
      gender:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: seekastyle@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /login:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: 必填
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 1-ok 0-fail
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: 使用者登錄
      tags:
      - Common
  /user/change-password:
    put:
      consumes:
      - application/json
      description: update user login password
      parameters:
      - description: 必填
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.UserChangePwdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: 修改使用者密碼
      tags:
      - User
  /user/info:
    get:
      consumes:
      - application/json
      description: get user info data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetResponse'
      summary: 查詢使用者資訊
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: add user
      parameters:
      - description: 必填
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: 使用者註冊
      tags:
      - User
swagger: "2.0"
