package main

import (
	"net/http"
	"github.com/gin-gonic/gin"
	"golang-demo/src/handler"//golang-demo是 專案名稱
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"golang-demo/src/docs" // docs is generated by Swag CLI, you have to import it.
)


// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email seekastyle@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @termsOfService http://swagger.io/terms/
func main() {
	// 初始化引擎
	docs.SwaggerInfo.Title = "Golang-Demo Swagger API"
	docs.SwaggerInfo.Description = "This is a sample server Golang-Demo server."
	docs.SwaggerInfo.Version = "1.0.0"
	docs.SwaggerInfo.Host = "localhost:9205"
	docs.SwaggerInfo.BasePath = ""
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	engine := gin.Default()
	engine.GET("/swagger/*any", ginSwagger.DisablingWrapHandler(swaggerFiles.Handler, "NAME_OF_ENV_VARIABLE"))
	// 注册一个路由和处理函数
	engine.Any("/", WebRoot)
	engine.POST("/login", handler.PostLogin)
	user := engine.Group("user")
	user.GET("/info", handler.GetUserInfoByAccount)
	// user.GET("/:userID", userhandler.GetUserInfo)
	user.POST("/register", handler.PostRegister)
	user.PUT("/change-password", handler.PutUserChangePassword)

	// 绑定端口，然后启动应用
	engine.Run(":9205")
}

// WebRoot is ...
func WebRoot(context *gin.Context) {
	context.String(http.StatusOK, "hello, world")
}
